In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
dt = pd.read_excel("./昌平2015大气.xlsx")
data = dt.iloc[:,6:11].values
target = dt.iloc[:,11].values
print(data)
# print(target.shape)

[[  12.    18.    37.     0.5   21. ]
 [  13.    24.    35.     0.4   16. ]
 [   3.     5.    54.     0.3   14. ]
 ..., 
 [  16.    97.     3.     2.    97. ]
 [  13.    99.     2.     1.9   93. ]
 [  12.   101.     3.     2.7  128. ]]


In [3]:
x_train,x_test,y_train,y_test = train_test_split(data,target,test_size=0.25,random_state=1)
# 特征工程
std_x = StandardScaler()
x_train = std_x.fit_transform(x_train)
x_test = std_x.transform(x_test)
std_y = StandardScaler()
y_train = std_y.fit_transform(y_train.reshape(-1,1))
y_test = std_y.transform(y_test.reshape(-1,1))
print(x_train)


[[-0.13235062  0.85052097 -1.0152406   0.19056599  0.17446953]
 [ 3.86281547  2.17682376 -0.80912436  0.39374816  1.1038579 ]
 [ 0.24053155 -0.63367502 -0.09708643 -0.04387497 -0.22031491]
 ..., 
 [ 1.5189847   0.28210548 -0.80912436  0.08116021  0.00997601]
 [-0.50523279 -0.9494614   0.55873798 -0.04387497  0.09222277]
 [ 1.89186687  0.66104914 -0.86533788  0.08116021  0.17446953]]


D:\anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [4]:
from sklearn.linear_model import LinearRegression,SGDRegressor,Ridge
lin_reg = LinearRegression()
lin_reg.fit(x_train, y_train)
lin_reg.intercept_,lin_reg.coef_

(array([ -3.24073962e-18]),
 array([[ 0.09338407,  0.5297783 ,  0.12915831,  0.01767744,  0.31558916]]))

In [5]:
print("训练集准确率：",lin_reg.score(x_train,y_train))
print("测试集准确率：",lin_reg.score(x_test,y_test))

训练集准确率： 0.54150007433
测试集准确率： 0.490297727576


In [6]:
lr_1 = SGDRegressor()
lr_1.fit(x_train,y_train)
print("训练集准确率：",lr_1.score(x_train,y_train))
print("测试集准确率：",lr_1.score(x_test,y_test))
print(lr_1.coef_,lr_1.intercept_)

训练集准确率： 0.539889247331
测试集准确率： 0.489210206814
[ 0.10848609  0.54221719  0.12088167  0.04045573  0.29403227] [-0.00778458]


D:\anaconda\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
D:\anaconda\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
lr_2 = Ridge()
lr_2.fit(x_train,y_train)
print("训练集准确率：",lr_2.score(x_train,y_train))
print("测试集准确率：",lr_2.score(x_test,y_test))
print(lr_1.coef_,lr_1.intercept_)

训练集准确率： 0.541500060328
测试集准确率： 0.490294555216
[ 0.10848609  0.54221719  0.12088167  0.04045573  0.29403227] [-0.00778458]


In [9]:
print(data.shape)
print(target.shape)

(8472, 5)
(8472,)


In [10]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
pca.fit(data)
print (pca.explained_variance_ratio_)

[ 0.78368602  0.17066467  0.03156934  0.01213733  0.00194265]
